version: "3.8"

services:

    fast_api_mvp:
        build: ""
        command:
            - /bin/sh
            - -c
            - |
                echo "wait for 30 seconds"
                sleep 30
                uvicorn backend.run:application --host 0.0.0.0 --port 2309 --reload --timeout-keep-alive 1000
        volumes:
            - .:/backend/app
        env_file:
            - backend/.env
        logging:
          options:
            max-size: 10m
        deploy:
          resources:
            reservations:
              memory: 20M
        depends_on:
          - db_mvp
          - broker
        ports:
            - 2309:2309

    db_mvp:
        restart: always
        image: postgres:15.3
        container_name: db_mvp
        env_file:
            - backend/.env
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 8585:8080
        logging:
          driver: none

    broker:
        image: apache/kafka:latest
        restart: always
        container_name: broker
        env_file:
            - backend/.env
        ports:
            - 9092:9092
            - 9093:9093
        logging:
          driver: none

volumes:
    postgres_data: